name: CI/CD for Next.js on Vercel

on:
  push:
    branches:
      - main # またはデフォルトのブランチ名

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Next.jsの推奨バージョン

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint ./src

    - name: Build the project
      run: npm run build

    - name: Run Jest tests (if you have them)
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' # またはデフォルトのブランチ名

    steps:
    - name: Deploy to Vercel
      run: |
        npm i -g vercel
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

